name: Continous Integration
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Install dependecies
        run:  | 
            npm install
            npm ci
      - name: Run tests
        run: npm test
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: streamline-back-office
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .